Repository Team-PLAT/Plat-iOS, pull requests merged in 2024-08, with the labels that each got.

#25 [PR/#20] 아서 컨벤션 작업
  PLAT/PLAT/Helper/Helper+Lottie.swift
  PLAT/PLAT/Helper/Helper+PretendardFont.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
Labels: Reviewing, CHORE, 아야

#29 [PR/#28] entity 생성
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Entity/Location.swift
  PLAT/PLAT/Domain/Entity/Music.swift
  PLAT/PLAT/Domain/Entity/Platter.swift
  PLAT/PLAT/Domain/Entity/Playlist.swift
  PLAT/PLAT/Domain/Entity/Track.swift
  PLAT/PLAT/Domain/Entity/User.swift
Labels: Reviewing, FEAT, 아야

#38 [Sub-PR/#31] Track Map
  PLAT/.swiftlint.yml
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/StubMusicController.swift
  PLAT/PLAT/Data/StubTrackMapService.swift
  PLAT/PLAT/Data/StubTrackService.swift
  PLAT/PLAT/Domain/Entity/Place.swift
  PLAT/PLAT/Domain/Entity/Track.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/TrackMapServiceInterface.swift
  PLAT/PLAT/Domain/Interface/TrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackMapUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/img_letsplat.svg
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Mask group.png
Labels: 톨털

#37 [Sub-PR/#32] Track Detail
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Helper/Helper+DateFormatter.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Helper/Helper+StringFormatter.swift
  PLAT/PLAT/Presentaion/Component/DismissButton.swift
  PLAT/PLAT/Presentaion/Component/MusicIndicator.swift
  PLAT/PLAT/Presentaion/Component/MusicSeekBar.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_testBackground.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_testBackground.imageset/IMG_5588 1.png
Labels: 톨털

#41 [PR/#30] TrackFeedView UI 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Helper/Helper+FeedDateFormatter.swift
  PLAT/PLAT/Helper/Helper+RoundedCorner.swift
  PLAT/PLAT/Presentaion/FeedView.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_feedloacation.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_feedloacation.imageset/img_feedloacation.png
  PLAT/PLAT/Resource/Assets.xcassets/img_feedlogo.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_feedlogo.imageset/img_feedlogo.svg
Labels: Reviewing, FEAT, 아야

#34 [PR/#31] TrackMap 관련 UseCase 및 Interface 구축
  PLAT/.swiftlint.yml
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/StubMusicController.swift
  PLAT/PLAT/Data/StubTrackMapService.swift
  PLAT/PLAT/Data/StubTrackService.swift
  PLAT/PLAT/Domain/Entity/Place.swift
  PLAT/PLAT/Domain/Entity/Track.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/TrackMapServiceInterface.swift
  PLAT/PLAT/Domain/Interface/TrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackMapUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/img_letsplat.svg
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Mask group.png
Labels: In Progress, FEAT, 톨털

#42 [Sub develop/#31] develop머지를 위한 PR
  PLAT/.swiftlint.yml
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/StubMusicController.swift
  PLAT/PLAT/Data/StubTrackMapService.swift
  PLAT/PLAT/Data/StubTrackService.swift
  PLAT/PLAT/Domain/Entity/Place.swift
  PLAT/PLAT/Domain/Entity/Track.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/TrackMapServiceInterface.swift
  PLAT/PLAT/Domain/Interface/TrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackMapUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_letsplat.imageset/img_letsplat.svg
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_marker.imageset/Mask group.png
Labels: 톨털

#33 [PR/#32] TrackDetail View & UseCase 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Helper/Helper+DateFormatter.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Helper/Helper+StringFormatter.swift
  PLAT/PLAT/Presentaion/Component/DismissButton.swift
  PLAT/PLAT/Presentaion/Component/MiniMusicPlayer.swift
  PLAT/PLAT/Presentaion/Component/MusicIndicator.swift
  PLAT/PLAT/Presentaion/Component/MusicSeekBar.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_testBackground.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_testBackground.imageset/IMG_5588 1.png
Labels: Reviewing, FEAT, 톨털

#48 [PR/#35] PlatProcessingView 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Presentaion/Platting/PlattingView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT, 아야

#49 [PR/#47] TrackFeedView 더미데이터 연결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/FeedView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
Labels: Reviewing, FEAT, 아야

#50 [PR/#39] TrackDetailView Spotify Logic
  PLAT/.swiftlint.yml
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/App/AppDelegate.swift
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/App/SceneDelegate.swift
  PLAT/PLAT/Data/DTO/SpotifyTrackDTO.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/SpotifyMusicController.swift
  PLAT/PLAT/Data/StubMusicController.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Helper/Helper+Log.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Info.plist
  PLAT/PLAT/Presentaion/Component/MusicIndicator.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
Labels: Reviewing, FEAT, 톨털

#53 [PR/#52] NetworkManager 수정
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Info.plist
  PLAT/PLAT/Network/NetworkManager.swift
  PLAT/PLAT/Network/Service/Dto/BaseResponse.swift
  PLAT/PLAT/Network/Service/Dto/NetworkError.swift
  PLAT/PLAT/Network/Service/Dto/TrackDetail/TrackDetailRequest.swift
  PLAT/PLAT/Network/Service/Dto/TrackDetail/TrackDetailResponse.swift
  PLAT/PLAT/Network/Service/TrackFeedService.swift
Labels: Reviewing, FEAT, 아야

#58 [PR/#54] TrackFeedView 추가 작업
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Data/FeedTrackService.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Domain/Interface/FeedTrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/FeedTrackUseCase.swift
  PLAT/PLAT/Network/Dto/TrackDetailResponse.swift
  PLAT/PLAT/Network/NetworkManager.swift
  PLAT/PLAT/Network/Service/Dto/NetworkError.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
Labels: Reviewing, FEAT, 아야

#55 [PR/#44] TrackMapView 추가작업
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/LocationManager.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/StubTrackMapService.swift
  PLAT/PLAT/Domain/Interface/TrackMapServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackMapUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Platting/PlattingView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT, 톨털

#60 [PR/#59] TrackDetailView 기능 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/App/SceneDelegate.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Data/SpotifyMusicController.swift
  PLAT/PLAT/Domain/Constant/Constant.swift
  PLAT/PLAT/Domain/Entity/Playlist.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Component/MusicIndicator.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackAppendToPlaylistSheet.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/SystemImage/SystemImage.swift
Labels: Reviewing, FEAT

#24 [PR/#23] 애플 뮤직 권한 요청 로직 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/Data/AppleMusicAccountService.swift
  PLAT/PLAT/Data/AppleMusicController.swift
  PLAT/PLAT/Data/DTO/AppleMusicDTO.swift
  PLAT/PLAT/Data/MockDataBuilder.swift
  PLAT/PLAT/Domain/Interface/StreamAccountServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/StreamAccountUseCase.swift
  PLAT/PLAT/Info.plist
  PLAT/PLAT/Network/Config.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
Labels: Reviewing, FEAT

#63 [PR/#62] 톨털팀 첫번째 스프린트 보완사항 적용입니다.
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/Data/AppleSocialLoginService.swift
  PLAT/PLAT/Data/StubUserProfileService.swift
  PLAT/PLAT/Data/StubUserService.swift
  PLAT/PLAT/Data/StubUserSessionService.swift
  PLAT/PLAT/Domain/Entity/StreamAccount.swift
  PLAT/PLAT/Domain/Interface/SocialLoginServiceInterface.swift
  PLAT/PLAT/Domain/Interface/UserProfileServiceInterface.swift
  PLAT/PLAT/Domain/Interface/UserSessionServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/AuthUseCase.swift
  PLAT/PLAT/Domain/UseCase/LoginUseCase.swift
  PLAT/PLAT/Domain/UseCase/UserUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Component/ListRadioButton.swift
  PLAT/PLAT/Presentaion/Component/ListSection.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/Register/LoginView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/Settings/AboutPlatSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/AccountSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/NicknameSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/StreamAccountSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/UserDetailView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/Icons.xcassets/icn_appleMusic.imageset/AppleMusic Icon.svg
  PLAT/PLAT/Resource/Icons.xcassets/icn_appleMusic.imageset/Contents.json
  PLAT/PLAT/Resource/Icons.xcassets/icn_chevronRight.imageset/Contents.json
  PLAT/PLAT/Resource/Icons.xcassets/icn_chevronRight.imageset/Frame 446.svg
  PLAT/PLAT/Resource/Icons.xcassets/icn_spotify.imageset/Contents.json
  PLAT/PLAT/Resource/Icons.xcassets/icn_spotify.imageset/plat_Spotify.svg
Labels: Reviewing, CHORE, 톨털
