Repository Team-PLAT/Plat-iOS, pull requests merged in 2024-09, with the labels that each got.

#68 [PR/#67] API EndPoint 관리 객체 생성
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/DTO/SpotifyTrackDTO.swift
  PLAT/PLAT/Data/Service/AppleMusicAccountService.swift
  PLAT/PLAT/Data/Service/AppleMusicController.swift
  PLAT/PLAT/Data/Service/AppleSocialLoginService.swift
  PLAT/PLAT/Data/Service/FeedTrackService.swift
  PLAT/PLAT/Data/Service/LocationManager.swift
  PLAT/PLAT/Helper/Helper+RawRepresentable.swift
  PLAT/PLAT/Network/API/API.swift
  PLAT/PLAT/Network/API/PlatAPI.swift
  PLAT/PLAT/Network/Service/DTO/BaseResponse.swift
  PLAT/PLAT/Network/Service/DTO/NetworkError.swift
  PLAT/PLAT/Network/Service/DTO/TrackDetail/TrackDetailRequest.swift
  PLAT/PLAT/Network/Service/DTO/TrackDetail/TrackDetailResponse.swift
Labels: Reviewing, FEAT

#73 [PR/#71] API Log 객체 구현 및 NetworkClient 객체 수정
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Constant/Data/DTO/AppleMusicDTO.swift
  PLAT/PLAT/Domain/Constant/Data/Service/AppleMusicAccountService.swift
  PLAT/PLAT/Domain/Constant/Data/Service/AppleMusicController.swift
  PLAT/PLAT/Domain/Constant/Data/Service/AppleSocialLoginService.swift
  PLAT/PLAT/Domain/Constant/Data/Service/FeedTrackService.swift
  PLAT/PLAT/Domain/Constant/Data/Service/LocationManager.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubInfoService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubMusicController.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubStreamAccountService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubTrackAppendService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubTrackMapService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubTrackService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubUserProfileService.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubUserSessionService.swift
  PLAT/PLAT/Network/APIMethod.swift
  PLAT/PLAT/Network/HTTPMethod.swift
  PLAT/PLAT/Network/NetworkLog.swift
  PLAT/PLAT/Network/NetworkManager.swift
  PLAT/PLAT/Network/Service/DTO/BaseResponse.swift
  PLAT/PLAT/Network/Service/DTO/NetworkError.swift
  PLAT/PLAT/Network/Service/TrackFeedService.swift
Labels: Reviewing, FEAT

#76 [PR/#74] TrackDetailViw UI 업데이트
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Network/HTTPMethod.swift
  PLAT/PLAT/Presentaion/Component/ToastMessage.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackAppendToPlaylistSheet.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/SystemImage/SystemImage.swift
Labels: Reviewing, FEAT

#72 [PR/#69] 트랙 API 연결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT.xcodeproj/xcshareddata/xcschemes/PLAT.xcscheme
  PLAT/PLAT/Network/Service/DTO/NetworkError.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/FetchTrackDetailAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/FetchTrackFeedAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/FetchTrackMapAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/LikeTrackAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/ReportTrackAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackAPI/UploadTrackAPI.swift
  PLAT/PLAT/Network/Service/DTO/TrackDetail/TrackDetailRequest.swift
  PLAT/PLAT/Network/Service/DTO/TrackDetail/TrackDetailResponse.swift
  PLAT/PLAT/Network/Service/TrackFeedService.swift
  PLAT/PLAT/Network/Service/TrackService.swift
Labels: Reviewing, FEAT

#80 [PR/#79] NetworkClient 수정
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Network/Service/TrackService.swift
Labels: Reviewing, FEAT

#83 [PR/#77] TrackAppendView 추가 작업
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendContentView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: FEAT, 아야

#82 [PR/#78] 멤버 API 연결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Network/API/PlatAPI.swift
  PLAT/PLAT/Network/Service/DTO/ImageAPI/UploadImageAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/FetchProfileAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/FetchProfileStreamTypeAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/ResignAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/UpdateProfileAvatarAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/UpdateProfileNicknameAPI.swift
  PLAT/PLAT/Network/Service/DTO/MemberAPI/UpdateProfileStreamTypeAPI.swift
  PLAT/PLAT/Network/Service/ImageService.swift
  PLAT/PLAT/Network/Service/MemberService.swift
Labels: Reviewing, FEAT

#70 [PR/#66] 애플 뮤직 관련 추가 수정
  PLAT/PLAT/Domain/Constant/Data/DTO/AppleMusicDTO.swift
  PLAT/PLAT/Domain/Constant/Data/Service/AppleMusicAccountService.swift
  PLAT/PLAT/Domain/Constant/Data/Service/AppleMusicController.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Domain/Constant/Data/Stub/StubMusicController.swift
  PLAT/PLAT/Domain/Entity/Track.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/StreamAccountServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/FeedTrackUseCase.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackDetailUseCase.swift
  PLAT/PLAT/Presentaion/Component/MiniMusicPlayer.swift
  PLAT/PLAT/Presentaion/Component/MusicSeekBar.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT

#89 [PR/#85] Develop 업데이트 사항 중간 MERGE
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Data/DTO/AppleMusicDTO.swift
  PLAT/PLAT/Data/Network/API/PlatAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/ImageAPI/UploadImageAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/FetchProfileAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/FetchProfileStreamTypeAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/ResignAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/UpdateProfileAvatarAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/UpdateProfileNicknameAPI.swift
  PLAT/PLAT/Data/Network/Service/DTO/MemberAPI/UpdateProfileStreamTypeAPI.swift
  PLAT/PLAT/Data/Network/Service/ImageService.swift
  PLAT/PLAT/Data/Network/Service/MemberService.swift
  PLAT/PLAT/Data/Service/AppleMusicAccountService.swift
  PLAT/PLAT/Data/Service/AppleMusicController.swift
  PLAT/PLAT/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Data/Stub/StubMusicController.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/StreamAccountServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/FeedTrackUseCase.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackUseCase.swift
  PLAT/PLAT/Presentaion/Component/MiniMusicPlayer.swift
  PLAT/PLAT/Presentaion/Component/MusicSeekBar.swift
  PLAT/PLAT/Presentaion/Feed/FeedView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: FEAT

#91 [PR/#86] TrackAppendSearchView Edit
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Constant/Data/Stub/StubTrackAppendService.swift
  PLAT/PLAT/Domain/Interface/TrackAppendServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackAppendUseCase.swift
  PLAT/PLAT/Helper/Helper+View.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendSearchView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT, CHORE

#93 [PR/#92] TrackAppendContentView Edit
  PLAT/PLAT/Data/Stub/StubTrackAppendService.swift
  PLAT/PLAT/Domain/Interface/TrackAppendServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackAppendUseCase.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendContentView.swift
Labels: Reviewing, FEAT, CHORE

#96 [PR/#95] AppendPlaylist 뷰 UI 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Presentaion/Playlist/AppendPlaylistView.swift
Labels: Reviewing, FEAT

#98 [PR/#97] PlaylistDetail 뷰 UI 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailView.swift
Labels: Reviewing, FEAT

#87 [PR/#84] PlaylistView 작업
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Data/Stub/StubPlaylistService.swift
  PLAT/PLAT/Domain/Interface/PlaylistServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/PlaylistUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
  PLAT/PLAT/Resource/Assets/Icons.xcassets/icn_verticalDots.imageset/Contents.json
  PLAT/PLAT/Resource/Assets/Icons.xcassets/icn_verticalDots.imageset/icn_verticalDots.svg
Labels: Reviewing, FEAT

#99 [PR/#90] 애플 뮤직 오류 수정 & PlaylistDetails 뷰 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PLAT/PLAT/Data/Service/AppleMusicController.swift
  PLAT/PLAT/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Data/Stub/StubMusicController.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsEditView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailView.swift
  PLAT/PLAT/Resource/SystemImage/SystemImage.swift
Labels: Reviewing, FEAT

#108 [Feat/#107] 커스텀 NavigationTitle 및 Search bar 구현 완료
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
Labels: Reviewing, FEAT

#110 [PR/#106] TrackUseCase 정리
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Data/PlatService/Service/TrackService/TrackServiceImpl.swift
  PLAT/PLAT/Data/Stub/StubTrackService.swift
  PLAT/PLAT/Domain/Interface/TrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackFeed/TrackFeedView.swift
Labels: Reviewing, FEAT

#112 [PR/#109] PathModel을 통한 PlaylistView간 Navigation 전환 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Path/PathModel/PathModel+ViewBuilder.swift
  PLAT/PLAT/Domain/Path/PathType/Screen.swift
  PLAT/PLAT/Presentaion/Playlist/AppendPlaylistView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsEditView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
Labels: Reviewing, FEAT

#118 [PR/#113] Login API 연결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT.xcodeproj/xcshareddata/xcschemes/PLAT.xcscheme
  PLAT/PLAT/Component/PlatProgressView.swift
  PLAT/PLAT/Domain/UseCase/AuthUseCase.swift
  PLAT/PLAT/Presentaion/Register/SignUpOrInView.swift
  PLAT/PLAT/Presentaion/Settings/AccountSettingsView.swift
Labels: Reviewing, FEAT

#119 [PR/#100] TrackAppendSearchSheet UI 변경
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Component/PhotoAlbumPicker.swift
  PLAT/PLAT/Data/Stub/StubTrackAppendService.swift
  PLAT/PLAT/Domain/Path/PathModel/PathModel+ViewBuilder.swift
  PLAT/PLAT/Domain/Path/PathModel/PathModel.swift
  PLAT/PLAT/Domain/Path/PathModel/PathModelProtocol.swift
  PLAT/PLAT/Domain/Path/PathType/Sheet.swift
  PLAT/PLAT/Domain/UseCase/TrackAppendUseCase.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendContentSheet.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendSearchSheet.swift
Labels: Reviewing, FEAT

#116 [PR/#114] UserDetailView 프로필사진 변경 로직 구현
  PLAT/PLAT/Presentaion/Settings/UserDetailView.swift
Labels: Reviewing, FEAT

#115 [PR/#105] 구독 sheet 및 뷰 노래 재생 Usecase 해결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/AppleFrameworkService/Service/AppleMusicControllerServiceImpl.swift
  PLAT/PLAT/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Domain/Entity/Playlist.swift
  PLAT/PLAT/Domain/UseCase/MapUseCase.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/PlaylistUseCase.swift
  PLAT/PLAT/Presentaion/AppCoordinator/AppCoordinatorView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsEditView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackFeed/TrackFeedView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT

#124 [PR/#121] 프로젝트 파일 해결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Entity/User.swift
  PLAT/PLAT/Domain/UseCase/AuthUseCase.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackFeed/TrackFeedView.swift
Labels: Reviewing, FEAT

#129 [PR/#128] 역지오코딩 API 추가
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Data/PlatService/API/PlatAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/AddressAPI/ReverseGeocodeAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/TrackAPI/FetchTrackDetailAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/TrackAPI/FetchTrackFeedAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/TrackAPI/FetchTrackMapAPI.swift
  PLAT/PLAT/Data/PlatService/Service/AddressService/AddressRepository.swift
  PLAT/PLAT/Data/PlatService/Service/AddressService/AddressServiceImpl.swift
  PLAT/PLAT/Data/PlatService/Service/MemberService/MemberServiceImpl.swift
  PLAT/PLAT/Data/Stub/MockDataBuilder.swift
  PLAT/PLAT/Data/Stub/StubMemberService.swift
  PLAT/PLAT/Data/Stub/StubUserProfileService.swift
  PLAT/PLAT/Domain/Entity/Place.swift
  PLAT/PLAT/Domain/Entity/User.swift
  PLAT/PLAT/Domain/Interface/AddressServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/MapUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackUseCase.swift
  PLAT/PLAT/Presentaion/AppCoordinator/AppCoordinatorView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackFeed/TrackFeedView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT

#127 [PR/#126] 플리 뷰 디테일 수정
  PLAT/PLAT/Data/AppleFrameworkService/Service/AppleMusicControllerServiceImpl.swift
  PLAT/PLAT/Domain/UseCase/PlaylistUseCase.swift
  PLAT/PLAT/Presentaion/PlatProcessing/PlatProcessingFullScreen.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistDetailsEditView.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
  PLAT/PLAT/Resource/SystemImage/SystemImage.swift
Labels: Reviewing, FEAT

#125 [PR/#122] ReportView 및 신고하기 기능 구현
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Path/PathModel/PathModel+ViewBuilder.swift
  PLAT/PLAT/Domain/Path/PathType/Screen.swift
  PLAT/PLAT/Helper/Helper+UserDefaults.swift
  PLAT/PLAT/Presentaion/Report/ReportView.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendSearchSheet.swift
  PLAT/PLAT/Presentaion/TrackDetail/TrackDetailFullScreen.swift
  PLAT/PLAT/Presentaion/TrackFeed/TrackFeedView.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
Labels: Reviewing, FEAT

#130 [PR/#123] PlatProcessing FullScreen UI 수정
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Domain/Path/PathModel/PathModel+ViewBuilder.swift
  PLAT/PLAT/Presentaion/PlatProcessing/PlatProcessingFullScreen.swift
  PLAT/PLAT/Presentaion/TrackMap/TrackMapView.swift
  PLAT/PLAT/Resource/Assets/Assets.xcassets/img_playlistsave.imageset/Contents.json
  PLAT/PLAT/Resource/Assets/Assets.xcassets/img_playlistsave.imageset/img_playlistsave.png
Labels: Reviewing, FEAT

#133 [PR/#132] ProfileImage 업로드 API 연결
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Data/PlatService/Service/MemberService/MemberServiceImpl.swift
  PLAT/PLAT/Data/Stub/StubMemberService.swift
  PLAT/PLAT/Domain/Interface/MemberServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/AuthUseCase.swift
Labels: Reviewing, FEAT

#136 [PR/#134] Playlist API 연결
  PLAT/Config.xcconfig
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/DIContainer.swift
  PLAT/PLAT/Data/PlatService/API/PlatAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/AppendTrackToPlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/DeletePlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/FetchPlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/FetchPlaylistDetailAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/SearchPlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/UpdatePlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/PlaylistAPI/UploadPlaylistAPI.swift
  PLAT/PLAT/Data/PlatService/Service/PlaylistService/PlaylistRepository.swift
  PLAT/PLAT/Data/PlatService/Service/PlaylistService/PlaylistServiceImpl.swift
  PLAT/PLAT/Data/Stub/StubPlaylistService.swift
  PLAT/PLAT/Domain/Interface/PlaylistServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/PlaylistUseCase.swift
  PLAT/PLAT/Helper/Helper+Preview.swift
  PLAT/PLAT/Presentaion/Playlist/PlaylistView.swift
Labels: Reviewing, FEAT

#143 [PR/#131] 음악 검색 기능 수정
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/AppleFrameworkService/Service/AppleMusicControllerServiceImpl.swift
  PLAT/PLAT/Data/Stub/StubMusicController.swift
  PLAT/PLAT/Data/Stub/StubTrackAppendService.swift
  PLAT/PLAT/Domain/Interface/MusicControllerInterface.swift
  PLAT/PLAT/Domain/Interface/TrackAppendServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/MusicControlUseCase.swift
  PLAT/PLAT/Domain/UseCase/TrackAppendUseCase.swift
  PLAT/PLAT/Presentaion/TrackAppend/TrackAppendSearchSheet.swift
Labels: Reviewing, FEAT

#138 [PR/#137] 트랙 삭제 API 연결
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Data/PlatService/API/PlatAPI.swift
  PLAT/PLAT/Data/PlatService/DTO/TrackAPI/DeleteTrackAPI.swift
  PLAT/PLAT/Data/PlatService/Service/TrackService/TrackRepository.swift
  PLAT/PLAT/Data/PlatService/Service/TrackService/TrackServiceImpl.swift
  PLAT/PLAT/Data/Stub/StubTrackService.swift
  PLAT/PLAT/Domain/Interface/TrackServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/TrackUseCase.swift
Labels: Reviewing, FEAT
