Repository Team-PLAT/Plat-iOS, pull requests merged in 2024-07, with the labels that each got.

#9 [PR/#8] 첫번째 스프린트를 위한 폴더링 및 도메인 분석
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/App/PLATApp.swift
  PLAT/PLAT/ContentView.swift
  PLAT/PLAT/Data/LoginService.swift
  PLAT/PLAT/Domain/Entity/StreamAccount.swift
  PLAT/PLAT/Domain/Entity/User.swift
  PLAT/PLAT/Domain/Interface/InfoServiceInterface.swift
  PLAT/PLAT/Domain/Interface/LoginServiceInterface.swift
  PLAT/PLAT/Domain/Interface/StreamAccountServiceInterface.swift
  PLAT/PLAT/Domain/Interface/UserServiceInterface.swift
  PLAT/PLAT/Domain/UseCase/InfoUseCase.swift
  PLAT/PLAT/Domain/UseCase/LoginUseCase.swift
  PLAT/PLAT/Domain/UseCase/StreamAccountUseCase.swift
  PLAT/PLAT/Domain/UseCase/UserUseCase.swift
  PLAT/PLAT/Presentaion/Register/LoginView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
  PLAT/PLAT/Presentaion/Settings/AboutPlatSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/AccountSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/NicknameSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/StreamAccountSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/UserDetailView.swift
  PLAT/PLAT/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/Contents.json
Labels: Reviewing

#12 [PR/#10] 디자인 시스템 추가
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Helper/Helper+PretendardFont.swift
  PLAT/PLAT/Info.plist
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Resource/Colors.xcassets/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray1.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray2.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray3.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray4.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray5.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray6.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray7.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray8.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/GrayscaleColors/gray9.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/plat_black.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/plat_darkpurple.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/plat_lightpurple.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/plat_neon.colorset/Contents.json
  PLAT/PLAT/Resource/Colors.xcassets/PlatColors/plat_purple.colorset/Contents.json
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Black.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Bold.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-ExtraBold.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-ExtraLight.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Light.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Medium.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Regular.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-SemiBold.ttf
  PLAT/PLAT/Resource/Fonts/Pretendard/Pretendard-Thin.ttf
Labels: Reviewing

#17 [PR/#15] navigationPath 적용
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/Path/Path.swift
  PLAT/PLAT/Presentaion/Main/MainView.swift
  PLAT/PLAT/Presentaion/Settings/AccountSettingsView.swift
  PLAT/PLAT/Presentaion/Settings/UserDetailView.swift
Labels: Reviewing, FEAT, 톨털

#19 [PR#18] 카야 뷰 컨벤션 작업
  PLAT/PLAT.xcodeproj/project.pbxproj
  PLAT/PLAT/Domain/UseCase/LoginUseCase.swift
  PLAT/PLAT/Helper/Helper+Lottie.swift
  PLAT/PLAT/Presentaion/Register/LoginView.swift
  PLAT/PLAT/Presentaion/Register/OnboardingView.swift
  PLAT/PLAT/Resource/Assets.xcassets/img_headphone.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_headphone.imageset/headphone.png
  PLAT/PLAT/Resource/Assets.xcassets/img_plat.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_plat.imageset/plat.svg
  PLAT/PLAT/Resource/Assets.xcassets/img_weblink.imageset/Contents.json
  PLAT/PLAT/Resource/Assets.xcassets/img_weblink.imageset/plat_weblink.svg
Labels: Reviewing, CHORE, 아야
